// Tela de login
new PlayerText:texPlayerLoginScreen;
new Text:textLoginScreen[6];

// Tela de carregando
new Text:textLoading;

//cama
new Text:spawnSleepBag[7];

// Informações do player
new Text:textBoxInfo1;
new Text:textBoxInfo2;
new Text:textBoxInfo3;
new PlayerText:playerTextBoxInfo[MAX_PLAYERS];

// battle royale announce
new Text:textBattleAnnounce;

// Roleta de opções
new Text:TextDrawEmotes[10];

// change default skin
new Text:textChangeDSkin;

// Pontuação do player
new Text:textPoints[2];
new PlayerText:playerTextPoints[MAX_PLAYERS];
new PlayerText:textPlayerLevel[MAX_PLAYERS];
new PlayerText:textPlayerZp;

// base craft itens
new PlayerText:textAuthorize[MAX_PLAYERS];

// Intro
new PlayerText:textIntroducao[2][MAX_PLAYERS];
new Text:textIntroEnd[2];

// exp
new PlayerText:playerExp[5];

// Blocked account
new PlayerText:playerTextBlocked[2];
new Text:textBlockedAccount[2];

// admin mode
new Text:textAdminMode1;

// Configurações
new Text:textConfig[7];
new PlayerText:textPlayerConfig[MAX_PLAYERS];

// Server Restart
new Text:textServerRestart;

// info death
new PlayerText:textInfoDeath[MAX_PLAYERS];

// HUD
new Text:textBaseHud;
new PlayerText:playerHudTextdraw[10];

// Barulho
new Text:textBarulho;
new PlayerText:textPlayerBarulho[2];

// Craft
new PlayerText:playerTextDrawsCraft[12];

// Admin spec
new PlayerText:textAdminInfoSpec[MAX_PLAYERS];

// Coins
new Text:textShopCoins[13];
new PlayerText:textPlayerShopCoins[MAX_PLAYERS];
new PlayerText:textPlayerShopModel[6][MAX_PLAYERS];
new PlayerText:textPlayerShopName [6][MAX_PLAYERS];

// Inventário
new Text:textInventory[13];
new PlayerText:textInventoryCondicao;
new PlayerText:p_ItensInventory[8];
new PlayerText:p_DropInventory[8];
new PlayerText:textPlayerItens[2][MAX_PLAYERS];
new PlayerText:textPlayerDrop[2][MAX_PLAYERS];
new PlayerText:textPlayerPage[MAX_PLAYERS];
new PlayerText:textPlayerPageDrop[MAX_PLAYERS];
new PlayerText:textPlayerInventory[5];
new PlayerText:textPlayerItemHealth[MAX_PLAYERS];
new PlayerText:textPlayerDropHealth[MAX_PLAYERS];
new PlayerText:playerItemsEquip[3];
new PlayerText:playerHealthProtect;
new Text:textGasMask;
new Text:textLanterna;

// Audio plugin
new PlayerText:textAudioPlugin[MAX_PLAYERS];

// Box discription
new Text:serverBoxDiscription[2];
new PlayerText:boxDiscription[2];

// Loot atual
new PlayerText:textPlayerLoot[MAX_PLAYERS];

// Mapa
new Text:textMap[11];

// Hud - radar
new Text:textHud[3];

// Grupos
new Text:textGroups[26];
new PlayerText:textPlayerGroups[3][MAX_PLAYERS];
new PlayerText:textGroupMembersList[MAX_PLAYERS];

// Conquistas
new Text:textConquista[4];
new PlayerText:textPlayerConquista[2][MAX_PLAYERS];

// Camera item
new PlayerText:textCameraItem[MAX_PLAYERS];
new Text:boxDroppedItem1;
new Text:boxDroppedItem2;

// Chat textdraw
new PlayerText:textChat[5];

// Info box
new PlayerText:textInfoBox[3][MAX_PLAYERS];

// Velocimetro
new PlayerText:textVelocimetro[MAX_PLAYERS];

// Bússola
new PlayerText:textBussola[MAX_PLAYERS];

// Battle Royale
new Text:textBattleRoyale;

// Ranks
new Text:textServerRanks[7];
new PlayerText:textPlayerRanks[MAX_PLAYERS][5];
new PlayerText:PlayerTextDrawStatus[3];
