// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 
// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 
// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 

const s_Mochila 	= 0;
const s_Weap1 		= 1;
const s_Weap2       = 2;
const s_weap3       = 3;
const s_Colete      = 4;
const s_Capacete    = 5;
const s_Acessorio   = 6;
const s_Lanterna1   = 7;
const s_Lanterna2   = 8;
const s_GasMask     = 9;
