// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 
// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 
// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 
// Download > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - > www.dominiosamp.net - 

#define pastaPlayers    "ZNation/Players/%s.dat"
#define pastaInventario "ZNation/Inventory/%s.dat"
#define pastaTendas     "ZNation/Tendas/tenda_%d.ini"
#define pastaVehicles   "ZNation/Vehicles/veh_%d.ini"
#define pastaGroups     "ZNation/Groups/group_%d.ini"
#define pastaArvores    "ZNation/Itens/arvores.txt"
#define pastaPlayersDB  "ZNation/Players/znation.db"
#define pastaBasesDB    "ZNation/Bases/bases.db"
#define pastaLogs    	"ZNation/Logs/log_%s.txt"
#define pastaPagseguro  "ZNation/transacoes/%s.ini"
#define pastaKeys       "ZNation/Vehicles/keys.ini"
